---
title: "Charts Overview"
params:
  exchanges: Deutschland
  path_to_eod_data: data/EOD-Data.RData
---


```{r load, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE, echo=FALSE)


options("getSymbols.warning4.0"=FALSE)
suppressPackageStartupMessages(library(googleVis))
library(xts)
library(quantmod)
library(googleVis)
library(ggplot2)
library(reshape2)
library(bdscale)
library(RColorBrewer)
#library(RGoogleDocs)
library(knitr)


op <- options(gvis.plot.tag='chart')

# Lies Funktionen ein
source(file="01_functions.R")

# Lade EoD Daten
load("data/EOD-Data.RData")

# Filtere das Environment stcoks auf ein Subset, evtl. DAX30
dat <- read.csv("DAX40_ticker.csv")

```

## Charts und technische Indikatoren für eine Auswahl von Aktien

__Hier: Die DAX40 Unternehmen__

* Candlestick-Charts
* Einfache gleitende Durchschnitte (simple moving average SMA) für 50, 150, 200 Tage
* MACD mit Parametern (12, 26, 9)

```{r plot_charts, fig.show='hold', out.width="50%"}
for (i in 1:length(dat$Ticker)) {
  try(
    chartSeries(get(as.character(dat$Ticker[i]), envir=stocks), subset='last 4 months', 
                name=paste0(as.character(dat$Name[i]), "(", dat$Ticker[i], ")"),
                theme = chartTheme("white"),
                TA = c(addMACD(), addSMA(n = c(50,150, 200)))) 
    )
    try(message(paste0(as.character(dat$Name[i]), "(", dat$Ticker[i], ")",
                 index(tail(get(as.character(dat$Ticker[i]), envir=stocks),1))))
    )
}

```


-----
``` `r Sys.time()` ```   

END OF FILE
